# DEB specific CPack configuration parameters
set(CPACK_GENERATOR "${CPACK_GENERATOR};DEB")
execute_process(COMMAND lsb_release -cs OUTPUT_VARIABLE DEB_CODENAME OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND dpkg --print-architecture OUTPUT_VARIABLE DEB_ARCHITECTURE OUTPUT_STRIP_TRAILING_WHITESPACE)
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${DEB_ARCHITECTURE})
set(CPACK_DEBIAN_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}")

option(DEB_CODENAME_IN_RELEASE "Use <version>-<release>.<codename> versioning and the Debian default file name" OFF)

if (DEB_CODENAME_IN_RELEASE)
  # Produces e.g. maxscale_23.08.12-1.noble_amd64.deb, the layout expected by repository upload tooling.
  set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
  set(CPACK_DEBIAN_PACKAGE_RELEASE "${MAXSCALE_BUILD_NUMBER}.${DEB_CODENAME}")
  set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
else()
  set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}~${DEB_CODENAME}")
  set(CPACK_DEBIAN_PACKAGE_RELEASE "${MAXSCALE_BUILD_NUMBER}")
endif()

if(TARGET_COMPONENT STREQUAL "core" OR TARGET_COMPONENT STREQUAL "all")
  set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
  set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_BINARY_DIR}/postinst;${CMAKE_BINARY_DIR}/prerm")

  # Some modules were moved from maxscale-experimental into maxscale in 6. The
  # version 6 modules must replace the 2.5 ones.
  set(CPACK_DEBIAN_PACKAGE_REPLACES "maxscale-experimental (<< 6)")

  # Extra packages this one replaces, e.g. "maxscale" when building under a different package name.
  if (DEB_EXTRA_REPLACES)
    set(CPACK_DEBIAN_PACKAGE_REPLACES "${CPACK_DEBIAN_PACKAGE_REPLACES}, ${DEB_EXTRA_REPLACES}")
  endif()
elseif(TARGET_COMPONENT STREQUAL "devel")
  set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}\n${DESCRIPTION_TEXT}")
endif()

if(EXTRA_PACKAGE_DEPENDENCIES)
  set(CPACK_DEBIAN_PACKAGE_DEPENDS "${EXTRA_PACKAGE_DEPENDENCIES}")
endif()

if (WITH_SYSTEM_NODEJS)
  set (CPACK_DEBIAN_PACKAGE_DEPENDS "nodejs (>= ${MINIMUM_NODEJS_VERSION})")
endif()

if (WITH_VALGRIND)
  if (CPACK_DEBIAN_PACKAGE_DEPENDS)
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "${CPACK_DEBIAN_PACKAGE_DEPENDS}, valgrind")
  else()
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "valgrind")
  endif()
endif()

message(STATUS "Generating DEB packages for ${DEB_ARCHITECTURE}")
